line-length = 100
target-version = "py312"
src = ["app", "tests", "migrations"]
extend-exclude = [".venv", ".pytest_cache", ".ruff_cache", ".terraform"]

[lint]
select = ["E", "F", "W", "I", "UP", "B"]
ignore = ["B008", "E501"]

[lint.isort]
known-first-party = ["app"]
