"""baseline schema

Revision ID: abff2336451a
Revises:
Create Date: 2026-03-30 20:06:06.005163
"""

from __future__ import annotations

from typing import Any

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
REVISION = "abff2336451a"
DOWN_REVISION = None
BRANCH_LABELS = None
DEPENDS_ON = None

globals()["revision"] = REVISION
globals()["down_revision"] = DOWN_REVISION
globals()["branch_labels"] = BRANCH_LABELS
globals()["depends_on"] = DEPENDS_ON


def get_dynamic_member(obj: Any, attribute_name: str) -> Any:
    """Return a dynamic attribute from an Alembic proxy object."""
    return getattr(obj, attribute_name)


def invoke_operation(name: str, *args: Any, **kwargs: Any) -> Any:
    """Call an Alembic operation through the dynamic operations proxy."""
    return get_dynamic_member(op, name)(*args, **kwargs)


def format_identifier(identifier: str) -> str:
    """Apply Alembic naming conventions to an identifier."""
    return get_dynamic_member(op, "f")(identifier)


def upgrade() -> None:
    """Create the baseline songs, playlists, and association tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    invoke_operation(
        "create_table",
        "playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    invoke_operation(
        "create_index",
        format_identifier("ix_playlists_id"),
        "playlists",
        ["id"],
        unique=False,
    )
    invoke_operation(
        "create_table",
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artist", sa.String(length=255), nullable=False),
        sa.Column("album", sa.String(length=255), nullable=True),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    invoke_operation(
        "create_index",
        format_identifier("ix_songs_id"),
        "songs",
        ["id"],
        unique=False,
    )
    invoke_operation(
        "create_table",
        "playlist_songs",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("playlist_id", "song_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the baseline association, songs, and playlists tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    invoke_operation("drop_table", "playlist_songs")
    invoke_operation("drop_index", format_identifier("ix_songs_id"), table_name="songs")
    invoke_operation("drop_table", "songs")
    invoke_operation("drop_index", format_identifier("ix_playlists_id"), table_name="playlists")
    invoke_operation("drop_table", "playlists")
    # ### end Alembic commands ###
